### ISSUE TITLE
entity types added to the nomoreportals:portal_allowed dont work ...

### ISSUE THREAD

**Issue by McReiz** [lukebemish/NoMorePortals#2] opened 2024-10-14 05:45 UTC
entity types added to the nomoreportals:portal_allowed tag will still be allowed through portals.

I'm using quilt 0.9.2 minecraft 1.20.1
Mods:
architectury-9.2.14-fabric.jar
cultural-delights-fabric-1.0.5+1.20.1.jar
FarmersDelight-1.20.1-2.1.6+refabricated.jar
kubejs-fabric-2001.6.5-build.14.jar
qfapi-7.6.0_qsl-6.2.0_fapi-0.92.2_mc-1.20.1
rhino-fabric-2001.2.3-build.6

nomoreportals-quilt-1.20-1.1.1

**Comment by lukebemish** [comment] 2024-10-14 06:57
I'm a bit confused what you're saying. Are you saying that entity types in that tag _are_ going through portals? For that tag, that should be the intended behavior -- normally no entity types can go through portals and that specifies exceptions.

**Comment by lukebemish** [comment] 2024-10-14 06:58
Or is the issue that entities _not_ in the tag are still allowed through portals? I can look into that.

**Comment by McReiz** [comment] 2024-10-14 07:02
> Or is the issue that entities _not_ in the tag are still allowed through portals? I can look into that.

Yesh, the issue that entities not in the tag are still allowed through portals

**Comment by lukebemish** [comment] 2024-10-14 23:11
Ah, yeah, bit of a goof on my end there -- I'll fix that when I've got a chance and release a new version, should be pretty easy.

**Comment by lukebemish** [comment] 2024-10-18 02:52
In theory fixed in 1.1.2; let me know if this is not the case.

**Closed as completed by lukebemish** 2024-10-18 02:52 UTC
